site_name: Ratemarkt Docs
site_url: http://docs.ratemarkt.com
site_description: 'Ratemartk Documentation and Knowledge Base Portal'
site_author: 'Ratemarkt Ltd.'

theme: 'material'
theme_dir: 'theme'

repo_name: 'ratemarkt/ratemarkt-docs'
repo_url: 'https://github.com/ratemarkt/ratemarkt-docs'
edit_uri: 'blob/master/docs'

extra_css:
  - 'css/extra.css'

extra_javascript:
  - 'js/feedback.js'

extra:
  palette:
    primary: 'Teal'
    accent: 'Deep Orange'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: 'img/logo.png'
  social:
    - type: 'globe'
      link: 'http://ratemarkt.com'
    - type: 'github-alt'
      link: 'https://github.com/ratemarkt'
    - type: 'twitter'
      link: 'https://twitter.com/ratemarkt'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/ratemarkt'
  feature:
    # tabs: true

markdown_extensions:
  - admonition
  - codehilite(guess_lang=false,linenums=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - fontawesome_markdown


copyright: 'Copyright &copy; 2017 - 2018 Ratemarkt Ltd.'

google_analytics:
  - 'UA-2040979-10'
  - 'auto'

pages:
- Home: 'index.md'
- 'Users Guide':
    - 'Getting Started': 'users_guide/getting_started.md'
- 'Api Docs':
    - 'Getting Started': 'api_docs/getting_started.md'
    - 'Authentication': 'api_docs/authentication.md'
    - 'Check Hotels Endpoint': 'api_docs/check_hotels.md'
    - 'Check Hotel Endpoint': 'api_docs/check_hotel.md'
    - 'Check Rate Endpoint': 'api_docs/check_rate.md'
    - 'Book Rate Endpoint': 'api_docs/book_rate.md'
    - 'Check Booking Endpoint': 'api_docs/check_booking.md'
    - 'Cancel Booking Endpoint': 'api_docs/cancel_booking.md'
- 'SDK Docs':
    - 'Getting Started': 'sdk_docs/getting_started.md'
- 'Supply Specs':
    - 'Getting Started': 'api_specs/getting_started.md'
- 'F.A.Q': faq.md
